# Generated by Django 5.0.7 on 2024-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal_admin', '0010_alter_event_details_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_details',
            name='event_budget',
        ),
        migrations.RemoveField(
            model_name='order',
            name='decoration_theam',
        ),
        migrations.AlterField(
            model_name='event_details',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
