# Generated by Django 5.0.6 on 2024-05-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
